import { Grant } from "./types";

// Preview grants shown on the landing page (before Supabase is connected)
export const dummyGrants: Omit<Grant, "created_at" | "updated_at">[] = [
  {
    id: "1",
    grant_name: "Community Development Block Grant",
    funding_organization: "U.S. Department of Housing and Urban Development",
    description:
      "Federal funding to support community development activities including affordable housing, anti-poverty programs, and infrastructure improvements.",
    application_url: "https://www.hud.gov/program_offices/comm_planning/cdbg",
    amount_min: 50000,
    amount_max: 500000,
    funding_type: "Federal",
    application_deadline: "Rolling - Year Round",
    grant_cycle: "Rolling",
    focus_area: "Community Development",
    geographic_eligibility: "National",
    eligible_org_types: "501(c)(3), gov units, tribal",
    org_budget_requirement: null,
    estimated_complexity: "Complex",
    requires_loi: "No",
    is_active: true,
  },
  {
    id: "2",
    grant_name: "Walmart Spark Good Local Grants",
    funding_organization: "Walmart Foundation",
    description:
      "Community-focused grants supporting local nonprofits in areas served by Walmart and Sam's Club stores.",
    application_url: "https://www.walmart.org/how-we-give/open-applications",
    amount_min: 250,
    amount_max: 5000,
    funding_type: "Corporate",
    application_deadline: "Cycle 1: Apr 15, 2026",
    grant_cycle: "Quarterly",
    focus_area: "General Operating",
    geographic_eligibility: "National",
    eligible_org_types: "501(c)(3)",
    org_budget_requirement: null,
    estimated_complexity: "Simple",
    requires_loi: "No",
    is_active: true,
  },
  {
    id: "3",
    grant_name: "Google Ad Grants",
    funding_organization: "Google",
    description:
      "Provides up to $10,000/month in free Google search advertising credits to help nonprofits reach donors and communities online.",
    application_url: "https://www.google.com/grants/",
    amount_min: 0,
    amount_max: 120000,
    funding_type: "Corporate",
    application_deadline: "Rolling - Year Round",
    grant_cycle: "Rolling",
    focus_area: "Technology",
    geographic_eligibility: "National",
    eligible_org_types: "501(c)(3)",
    org_budget_requirement: null,
    estimated_complexity: "Moderate",
    requires_loi: "No",
    is_active: true,
  },
  {
    id: "4",
    grant_name: "W.K. Kellogg Foundation Grants",
    funding_organization: "W.K. Kellogg Foundation",
    description:
      "Supports programs focused on thriving children, working families, and equitable communities with emphasis on racial equity.",
    application_url: "https://www.wkkf.org/grantseekers/",
    amount_min: 5000,
    amount_max: 500000,
    funding_type: "Foundation",
    application_deadline: "Rolling - Year Round",
    grant_cycle: "Rolling",
    focus_area: "Community Development",
    geographic_eligibility: "National",
    eligible_org_types: "501(c)(3)",
    org_budget_requirement: null,
    estimated_complexity: "Complex",
    requires_loi: "Yes",
    is_active: true,
  },
  {
    id: "5",
    grant_name: "NEA Our Town Grant",
    funding_organization: "National Endowment for the Arts",
    description:
      "Supports creative placemaking projects that integrate arts and culture into community revitalization efforts.",
    application_url: null,
    amount_min: 25000,
    amount_max: 150000,
    funding_type: "Federal",
    application_deadline: "Aug 5, 2026",
    grant_cycle: "Annual",
    focus_area: "Arts & Culture",
    geographic_eligibility: "National",
    eligible_org_types: "Nonprofits, Local Governments",
    org_budget_requirement: null,
    estimated_complexity: "Complex",
    requires_loi: "No",
    is_active: true,
  },
  {
    id: "6",
    grant_name: "USDA Rural Business Development Grant",
    funding_organization: "U.S. Department of Agriculture",
    description:
      "Provides funding for rural small business development, training, and technical assistance in communities with populations under 50,000.",
    application_url: null,
    amount_min: 10000,
    amount_max: 500000,
    funding_type: "Federal",
    application_deadline: "Jul 31, 2026",
    grant_cycle: "Annual",
    focus_area: "Community Development",
    geographic_eligibility: "Rural areas",
    eligible_org_types: "Nonprofits, Small Businesses, Cooperatives",
    org_budget_requirement: null,
    estimated_complexity: "Moderate",
    requires_loi: "No",
    is_active: true,
  },
  {
    id: "7",
    grant_name: "California Arts Council - Artists in Communities",
    funding_organization: "California Arts Council",
    description:
      "Supports artists working in partnership with community organizations to create art that addresses local needs.",
    application_url: null,
    amount_min: 5000,
    amount_max: 50000,
    funding_type: "State",
    application_deadline: "Apr 15, 2026",
    grant_cycle: "Annual",
    focus_area: "Arts & Culture",
    geographic_eligibility: "California",
    eligible_org_types: "Nonprofits, Individual Artists",
    org_budget_requirement: null,
    estimated_complexity: "Moderate",
    requires_loi: "No",
    is_active: true,
  },
  {
    id: "8",
    grant_name: "Kresge Foundation - Education Program",
    funding_organization: "The Kresge Foundation",
    description:
      "Supports postsecondary access and success for low-income, first-generation, and underrepresented students.",
    application_url: null,
    amount_min: 100000,
    amount_max: 750000,
    funding_type: "Foundation",
    application_deadline: "Rolling - Year Round",
    grant_cycle: "Rolling",
    focus_area: "Education",
    geographic_eligibility: "National",
    eligible_org_types: "Higher Education Institutions, Nonprofits",
    org_budget_requirement: null,
    estimated_complexity: "Complex",
    requires_loi: "Yes",
    is_active: true,
  },
  {
    id: "9",
    grant_name: "Texas Workforce Commission - Skills Development Fund",
    funding_organization: "Texas Workforce Commission",
    description:
      "Provides training grants to help Texas businesses and workers develop skills needed for job creation and economic growth.",
    application_url: null,
    amount_min: 10000,
    amount_max: 500000,
    funding_type: "State",
    application_deadline: "Dec 31, 2026",
    grant_cycle: "Rolling",
    focus_area: "Education",
    geographic_eligibility: "Texas",
    eligible_org_types: "Texas Businesses, Community Colleges, Nonprofits",
    org_budget_requirement: null,
    estimated_complexity: "Simple",
    requires_loi: "No",
    is_active: true,
  },
];
